In [ ]:
# Input Output, Data Types, Variables

print("Hello, World!")  # Output

name = input("Enter your name: ")  # Input
print("Welcome, ", name) # Output
print(f"Welcome, {name}")  # Output using f-string

age = 25 #Integer data type
isAboveThirty = False #Boolean data type
ipk = 3.75 #Float data type
name = "John Doe" #String data type

x, y = 20, 30 #Multiple variable assignment

Hello, World!
Welcome,  fadh
Welcome=fadh


In [2]:
# Operators

a = 10
b = 5

# Arithmetic Operators
print(a+b) # Addition
print(a-b) # Subtraction
print(a*b) # Multiplication
print(a/b) # Division
print(a//b) # Floor Division
print(a%b) # Modulus
print(a**b) # Exponentiation

# Comparison Operators
print(a==b) # Equal to
print(a!=b) # Not equal to
print(a>b) # Greater than
print(a<b) # Less than
print(a>=b) # Greater than or equal to
print(a<=b) # Less than or equal to

# Logical Operators
print(a>5 and b<10) # Logical AND
print(a>5 or b<10) # Logical OR
print(not(a>5 and b<10)) # Logical NOT

15
5
50
2.0
2
0
100000
False
True
True
False
True
False
True
True
False


In [3]:
# Conditional Statements
if age > 30:
    print("You are above 30 years old.")
else:
    print("You are 30 years old or younger.")

You are 30 years old or younger.


In [5]:
# Repetition Statements
# for loop
for i in range(5):
    print(i)
# range: start, stop, step
for i in range(1, 10, 2):
    print(i)

0
1
2
3
4
1
3
5
7
9


In [6]:
# while loop
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [8]:
# Functions
def add_numbers(x, y):
    return x + y

result = add_numbers(10, 5)
print(result) # Output: 15

def greet(name="fadh"):
    print(f"Hello, {name}!")
    
greet() # Output: Hello, fadh!

15
Hello, fadh!


In [ ]:
# Data structures
# List, Tuple, Set, Dictionary

In [33]:
# List: ordered, mutable, allows duplicates
my_list = [1, 2, 3, 4, 5]
print(my_list[0]) # Output: 1

list.append(int(6)) # Add element to the end of the list
list.insert(2, 10) # Insert element at index 2
list.remove(3) # Remove element from the list
list.sort(reverse=True) # Sort the list in ascending order
print(list) # Output: [10, 2, 4, 5, 6]

1


TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'int' object

In [14]:
# Tuple: ordered, immutable, allows duplicates
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple) # Output: 1



(1, 2, 3, 4, 5)


In [15]:
# set: unordered, mutable, no duplicates
my_set = {1, 2, 3, 4, 5}
print(my_set) # Output: {1, 2, 3, 4, 5}

my_set.add(6) # Add element to the set
my_set.remove(3) # Remove element from the set
print(my_set) # Output: {1, 2, 4, 5, 6}

{1, 2, 3, 4, 5}
{1, 2, 4, 5, 6}


In [ ]:
# Dictionary: unordered, mutable, key-value pairs
my_dict = {
    "name": "John",
    "age": 30, 
    "city": "New York"

}
print(my_dict["name"]) # Output: John
my_dict["age"] = 31 # Update value
my_dict["country"] = "USA" # Add new key-value pair
print(my_dict) # Output: {'name': 'John', 'age': 31, 'city': 'New York', 'country': 'USA'}

print(my_dict.keys()) # Output: dict_keys(['name', 'age', 'city', 'country']    
print(my_dict.values()) # Output: dict_values(['John', 31, 'New York', 'USA'])
print(my_dict.items()) # Output: dict_items([('name', 'John'), ('age', 31), ('city', 'New York'), ('country', 'USA')])

John
{'name': 'John', 'age': 31, 'city': 'New York', 'country': 'USA'}
dict_keys(['name', 'age', 'city', 'country'])
dict_values(['John', 31, 'New York', 'USA'])


In [18]:
# Arrays: ordered, mutable, allows duplicates
# Arr[start: stop: step]
numbers = [1, 2, 3, 4, 5]
print(numbers[0]) # Output: 1
print(numbers[1:4]) # Output: [2, 3, 4]
print(numbers[:2]) # Output: [1, 2]
print(numbers[2:]) # Output: [3, 4, 5]
print(numbers[::2]) # Output: [1, 3, 5]
print(numbers[::-1]) # Output: [5, 4, 3, 2, 1]

1
[2, 3, 4]
[1, 2]
[3, 4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]


In [ ]:
import numpy as np

numbers = [1,2,3,4,5]
arr = np.array(numbers)
print(type(numbers)) # Output: <class 'list'>
print(type(arr)) # Output: <class 'numpy.ndarray'>

arr2 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

# shape: ngasih tau size array dan dimensi
print(arr.shape) # Output: (5,)
print(arr2.shape) # Output: (2, 3)

# .ndim: ngasih tau dimensi array
print(arr.ndim) # Output: 1
print(arr2.ndim) # Output: 2

# dtype output: data type array
print(arr.dtype) # Output: int64
print(arr2.dtype) # Output: int64

# np.zeros: buat bikin array kosong
print(np.zeros((2, 3))) # Output: [[0. 0. 0.]

# np.empty: buat bikin array kosong tapi isinya random
print(np.empty((2, 3))) # Output: [[0. 0. 0.]

<class 'list'>
<class 'numpy.ndarray'>
(5,)
(2, 3)
1
2
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# np.arrange: buat bikin array dengan range tertentu
# arrange(start, stop, step)
print(np.arange(0, 10, 2)) # Output: [0 2 4 6 8]

#np.linspace: buat bikin array dengan range tertentu tapi dibagi rata
# linspace(start, stop, num)
print(np.linspace(0, 10, 5)) # Output: [ 0.  2.5  5.   7.5 10. ]

# np.random.rand: buat bikin array random
# rand(d0, d1, ..., dn)
print(np.random.rand(2, 3)) # Output: [[0.5488135  0.71518937 0.60276338]

# np.random.randint: buat bikin array random integer
# randint(low, high=None, size=None, dtype=int)
print(np.random.randint(0, 10, (2, 3))) # Output:

rng = np.random.default_rng()
int_array = rng.integers(low=1, high=10, size=(2, 3))
print(int_array)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[0.82155827 0.85500874 0.41632668]
 [0.83757423 0.3892249  0.42521802]]
[[6 3 6]
 [7 9 8]]
[[7 6 5]
 [1 7 7]]


In [30]:
# np.vstack: buat nambahin array secara vertikal
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr3 = np.vstack((arr1, arr2))
print(arr3) # Output: [[ 1  2  3]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# operasi scalar
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10) # Output: [[11 12 13]
print(arr - 10) # Output: [[-9 -8 -7]
print(arr * 10) # Output: [[10 20 30]

[[11 12 13]
 [14 15 16]]
[[-9 -8 -7]
 [-6 -5 -4]]
[[10 20 30]
 [40 50 60]]


In [31]:
# boolean Indexing
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[arr > 3]) # Output: [4 5 6] 

# and or not
print((arr > 3) & (arr < 6)) # Output: [[False False False]
print((arr > 3) | (arr < 6)) # Output: [[ True  True  True]
print(~(arr > 3)) # Output: [[ True  True  True]

[4 5 6]
[[False False False]
 [ True  True False]]
[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [False False False]]
